Output demo.mp4
Require nvim

Set Theme { "name": "vantAAAAAA","background":"#000000","cursor":"#AAAAAA"}
Set FontFamily "JetBrainsMono Nerd Font"
Set FontSize 34 
Set Width 1200
Set Height 600
Set TypingSpeed 100ms
Type@0ms "nvim -n example.dart"
Enter

Type "w"
Sleep 2s

Source open_code_action.tape
Type "snake"
Source show_typed_delay.tape
Enter
Source show_off_change_delay.tape

Source open_code_action.tape
Type "Pascal"
Source show_typed_delay.tape
Enter
Source show_off_change_delay.tape

Source open_code_action.tape
Type "UPPER"
Source show_typed_delay.tape
Enter
Source show_off_change_delay.tape

Source open_code_action.tape
Type "spaced"
Source show_typed_delay.tape
Enter
Sleep 1s

Type@200ms "wwww7l"
Type@0ms "v"
Sleep 10ms
Type@200ms "bbbbb"
Sleep 300ms

Source open_code_action.tape
Sleep 500ms
Type "camel"
Source show_typed_delay.tape
Enter
